# -*- coding: utf-8 -*-
"""wine_randomforest.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PodQlzASuo_ajIF8k3r57HfD_72OCGpq
"""

# Wine 데이터셋을 이용한 머신러닝 분류 모델 구현

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. 데이터셋 로드
wine = load_wine()
X = wine.data
y = wine.target

print("데이터 크기:", X.shape)
print("클래스 이름:", wine.target_names)

# 2. 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# 3. 머신러닝 모델 생성
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# 4. 모델 학습
model.fit(X_train, y_train)

# 5. 예측
y_pred = model.predict(X_test)

# 6. 정확도 출력
accuracy = accuracy_score(y_test, y_pred)

print("정확도:", accuracy)
print("\n분류 결과 보고서")
print(classification_report(y_test, y_pred, target_names=wine.target_names))